--
-- Author: Johnny Lee
-- Date: 2014-07-08 18:15:05
--

local DATA_KEYS = {}

DATA_KEYS.USER_DATA              = "USER_DATA"
DATA_KEYS.ROOM_INFO              = "ROOM_INFO"
DATA_KEYS.FRIEND_LIST            = "FRIEND_LIST"
DATA_KEYS.ROOM_CHAT_HISTORY      = "ROOM_CHAT_HISTORY"
DATA_KEYS.CURRENT_HALL_VIEW      = "CURRENT_HALL_VIEW"
DATA_KEYS.SIGNAL_STRENGTH        = "SIGNAL_STRENGTH"
DATA_KEYS.SIT_OR_STAND           = "SIT_OR_STAND"
DATA_KEYS.NEW_MESSAGE            = "NEW_MESSAGE"
DATA_KEYS.NEW_REWARD_TASK        = "NEW_REWARD_TASK"
DATA_KEYS.NEW_REWARD_ACHIEVE     = "NEW_REWARD_ACHIEVE"
DATA_KEYS.BIG_LA_BA_CHAT_HISTORY = "BIG_LA_BA_CHAT_HISTORY" -- 大喇叭消息
DATA_KEYS.NEW_FRIEND_DATA        = "NEW_FRIEND_MESSAGE"

return DATA_KEYS
