--
-- Author: tony
-- Date: 2014-07-15 19:05:10
--

local E = {} -- EVENT_NAMES

E.APP_ENTER_BACKGROUND = "APP_ENTER_BACKGROUND"
E.APP_ENTER_FOREGROUND = "APP_ENTER_FOREGROUND"

E.HALL_LOGIN_SUCC       = "HALL_LOGIN_SUCC"
E.HALL_LOGOUT_SUCC      = "HALL_LOGOUT_SUCC"
E.HALL_SHOW_MAIN_HALL   = "HALL_SHOW_MAIN_HALL"
E.HALL_SHOW_CHOOSE_ROOM = "HALL_SHOW_CHOOSE_ROOM"
E.ENTER_ROOM_WITH_DATA  = "ENTER_ROOM_WITH_DATA"
E.LOGIN_ROOM_SUCC       = "LOGIN_ROOM_SUCC"
E.LOGIN_ROOM_FAIL       = "LOGIN_ROOM_FAIL"
E.ROOM_CONN_PROBLEM     = "ROOM_CONN_PROBLEM"
E.SERVER_STOPPED        = "SERVER_STOPPED"
E.LOGOUT_ROOM_SUCC      = "LOGOUT_ROOM_SUCC"

E.UI_TAB_CHANGE = "UI_TAB_CHANGE"

E.ROOM_LOAD_HDDJ_NUM    = "ROOM_LOAD_HDDJ_NUM"
E.ROOM_REFRESH_HDDJ_NUM = "ROOM_REFRESH_HDDJ_NUM"

E.SEND_DEALER_CHIP_BUBBLE_VIEW = "SEND_DEALER_CHIP_BUBBLE_VIEW"
E.SVR_BROADCAST_ACT_STATE      = "SVR_BROADCAST_ACT_STATE" -- 活动完成
E.SVR_BROADCAST_ADD_EXP        = "SVR_BROADCAST_ADD_EXP"   -- 加经验动画
E.UPDATE_SEAT_ANTE_CHIP        = "UPDATE_SEAT_ANTE_CHIP"   -- 更新携带

E.SVR_BROADCAST_OPEN_MATCH            = "SVR_BROADCAST_OPEN_MATCH"    -- 打开比赛场

E.OPEN_BANK_POPUP_VIEW     = "OPEN_BANK_POPUP_VIEW"
E.SHOW_EXIST_PASSWORD_ICON = "SHOW_EXIST_PASSWORD_ICON"
E.OPEN_RESET_PASSWORD_DIALOG = "OPEN_RESET_PASSWORD_DIALOG" --打开重置密码框

E.SLOT_BUY_RESULT  = "SLOT_BUY_RESULT"
E.SLOT_PLAY_RESULT = "SLOT_PLAY_RESULT"

E.SVR_BROADCAST_BIG_LABA = "SVR_BROADCAST_BIG_LABA" --大喇叭消息

E.HIDE_GIFT_POPUP        = "HIDE_GIFT_POPUP"        -- 关闭礼物弹框
E.GET_CUR_SELECT_GIFT_ID = "GET_CUR_SELECT_GIFT_ID" -- 获取当前礼物ID

E.UPDATE_CUR_SELECT_GIFT_ID = "UPDATE_CUR_SELECT_GIFT_ID" --更新礼物ID

E.DOUBLE_LOGIN_LOGINOUT = "DOUBLE_LOGIN_LOGINOUT" -- 账号同时登录时退出消息

E.SVR_ERROR = "SVR_ERROR"

-- 比赛场相关内容
E.LOGIN_MATCH_SUCC = "LOGIN_MATCH_SUCC"  -- 登录比赛场成功
E.LOGIN_MATCH_FAIL = "LOGIN_MATCH_FAIL" -- 登录比赛场失败
E.LOGIN_MATCH_ROOM_SUCC = "LOGIN_MATCH_ROOM_SUCC" --登录比赛场房间成功
E.LOGIN_MATCH_ROOM_FAIL = "LOGIN_MATCH_ROOM_FAIL" --登录比赛场房间失败
E.MATCH_STARTING = "MATCH_STARTING"	-- 报名比赛已经开始
E.MATCH_JOIN_ERROR = "MATCH_JOIN_ERROR"	-- 进入比赛失败
E.MATCH_REG_COUNT = "MATCH_REG_COUNT"	-- 注册报名人数
E.MATCH_TIME_CHANGE = "MATCH_TIME_CHANGE" -- 时间变化
-- 积分商城
E.SCORE_MARKET_EXCHANGE = "SCORE_MARKET_EXCHANGE" -- 积分兑换
--点对点邀请好友
E.UPDATE_SEAT_INVITE_VIEW = "UPDATE_SEAT_INVITE_VIEW"

E.UPDATE_SEAT_PUSH_VIEW = "UPDATE_SEAT_PUSH_VIEW"  --推送召回

E.UPDATE_SEAT_INVITE_PLAY_VIEW = "UPDATE_SEAT_INVITE_PLAY_VIEW"--邀请进入房间一起玩牌

E.MATCH_ROOM_END = "MATCH_ROOM_END"	-- 比赛场结束

E.MATCH_ASYNC_RECORD_LOG = "MATCH_ASYNC_RECORD_LOG"	-- 同步个人档参赛记录

E.MATCH_ASYNC_HALL_RECORD_LOG = "MATCH_ASYNC_HALL_RECORD_LOG" -- 同步比赛场大厅相应比赛场的参赛记录

E.MATCH_ASYNC_STAT_LOG = "MATCH_ASYNC_STAT_LOG" -- 同步玩家个人档统计数据

E.SVR_CMD_USER_MATCH_SCORE = "SVR_CMD_USER_MATCH_SCORE"

E.MATCH_REWARDPOPUP_END = "MATCH_REWARDPOPUP_END"

E.CHOOSEARENA_PLAY_SHOW_ANIM = "CHOOSEARENA_PLAY_SHOW_ANIM"

E.CHOOSEARENA_PLAY_HIDE_ANIM = "CHOOSEARENA_PLAY_HIDE_ANIM"


E.LOGIN_DICE_SUCC = "LOGIN_DICE_SUCC"
E.LOGIN_DICE_FAIL = "LOGIN_DICE_FAIL"
E.DICE_CONN_PROBLEM = "DICE_CONN_PROBLEM"
E.LOGOUT_DICE_SUCC = "LOGOUT_DICE_SUCC"
E.ENABLED_EDITBOX_TOUCH = "ENABLED_EDITBOX_TOUCH" --打开输入框触摸事件
E.DISENABLED_EDITBOX_TOUCH = "DISENABLED_EDITBOX_TOUCH" --关闭输入框触摸事件

E.LOGIN_PDENG_SUCC = "LOGIN_PDENG_SUCC"
E.LOGIN_PDENG_FAIL = "LOGIN_PDENG_FAIL"
E.LOGOUT_PDENG_SUCC = "LOGOUT_PDENG_SUCC"

return E
